### ISSUE TITLE
Build and Deploy Validation

### ISSUE THREAD

**Issue by mdickson05** [enssol/web-app#104]
**Task**: Configure CI pipeline to build and run test suites in production-like environments before merging to main.
- **Actionable Step**: Set up builds and test execution in Alpine, Windows, and Mac environments; a test matrix
- **Actionable Step**: Set up pre-merge hook to ensure that app can compile and run appropriately in all environments before proceeding

**Comment by mdickson05** [comment]
The following should work for ubuntu testing. Turns out running custom Rust containers in Docker with Act is really difficult. This image works fine and comes with all the tools needed.
```
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  verify-build-and-run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build
      - run: cargo run
 ```
 
 According to the [repo that hosts the image](https://github.com/catthehacker/docker_images/pkgs/container/ubuntu):
> [/linux/ubuntu/rust](https://github.com/catthehacker/docker_images/blob/master/linux/ubuntu/scripts/rust.sh) - ghcr.io/catthehacker/ubuntu:act-* but with rust tools installed (rustfmt, clippy, cbindgen, etc.)

Worst comes to worst we can modify the Rust Dockerfile at the linked destination:
```
#!/bin/bash
# shellcheck disable=SC1091

set -Eeuxo pipefail

. /etc/environment
. /imagegeneration/installers/helpers/os.sh

export RUSTUP_HOME=/usr/share/rust/.rustup
export CARGO_HOME=/usr/share/rust/.cargo

printf "\n\t🐋 Installing dependencies 🐋\t\n"
apt-get -yq update
apt-get -yq install build-essential llvm libssl-dev

printf "\n\t🐋 Installing Rust 🐋\t\n"
curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable --profile=minimal

source "${CARGO_HOME}/env"

rustup component add rustfmt clippy

printf "\n\t🐋 Installing cargo-binstall 🐋\t\n"
# Pinned to commit-hash for latest release v1.4.7 to prevent accidental problems
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/f6a95fa733be466c0e66c360f52e1d6998e47f25/install-from-binstall-release.sh | bash

cargo binstall -y bindgen-cli cbindgen cargo-audit cargo-outdated

chmod -R 777 "$(dirname "${RUSTUP_HOME}")"

# cleanup
rm -rf "${CARGO_HOME}/registry/*"

sed "s|PATH=|PATH=${CARGO_HOME}/bin:|g" -i /etc/environment

cd /root
ln -sf "${CARGO_HOME}" .cargo
ln -sf "${RUSTUP_HOME}" .rustup
{
  echo "RUSTUP_HOME=${RUSTUP_HOME}"
  echo "CARGO_HOME=${CARGO_HOME}"
} | tee -a /etc/environment

printf "\n\t🐋 Installed RUSTUP 🐋\t\n"
rustup -V

printf "\n\t🐋 Installed CARGO 🐋\t\n"
cargo -V

printf "\n\t🐋 Installed RUSTC 🐋\t\n"
rustc -V

printf "\n\t🐋 Cleaning image 🐋\t\n"
apt-get clean
rm -rf /var/cache/* /var/log/* /var/lib/apt/lists/* /tmp/* || echo 'Failed to delete directories'

printf "\n\t🐋 Cleaned up image 🐋\t\n"
```
I will implement these changes once all the Rust conversion is complete

**Comment by mdickson05** [comment]
**Update: matrix strategy testing does not work on Github cloud** as only Linux environments are supported for containers.
![image](https://github.com/user-attachments/assets/7e679f71-fa5a-4b23-bd98-79d4eb68ade2)

Thankfully, this code works on the cloud:
```
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  verify-build-and-run:
    
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with cargo
        run: cargo build

      - name: Run the application
        run: cargo run
```
![image](https://github.com/user-attachments/assets/82295a15-eb43-4d50-826b-57f15943ba86)
